
server:
  port: 8000
# 정적파일 수정 시 새로고침 없어도 적용가능하도록 설정
spring:
  devtools:
    livereload:
      enabled: true

# 캐싱 기능 중지
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      jdbc-url: jdbc:h2:mem:testdb;database_to_upper=false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
#    schema, init data 자동 생성기능 on
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


